// <auto-generated />
using System;
using GlobalSoluction.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GlobalSoluction.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("GlobalSoluction.Models.AlertaEstufa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("DataResolucao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EstufaConfigId")
                        .HasColumnType("int");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("NivelCriticidade")
                        .HasColumnType("int");

                    b.Property<string>("Recomendacao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("Resolvido")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("SensorId")
                        .HasColumnType("int");

                    b.Property<string>("TipoAlerta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EstufaConfigId");

                    b.HasIndex("SensorId");

                    b.ToTable("AlertasEstufa");
                });

            modelBuilder.Entity("GlobalSoluction.Models.EstufaConfig", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativa")
                        .HasColumnType("tinyint(1)");

                    b.Property<decimal>("Co2IdealMax")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("Co2IdealMin")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("CulturaAtual")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("LocalOrbitalId")
                        .HasColumnType("int");

                    b.Property<decimal>("LuminosidadeIdealMax")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<decimal>("LuminosidadeIdealMin")
                        .HasPrecision(8, 2)
                        .HasColumnType("decimal(8,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("TemperaturaIdealMax")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("TemperaturaIdealMin")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("UmidadeArIdealMax")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("UmidadeArIdealMin")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("UmidadeSoloIdealMax")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.Property<decimal>("UmidadeSoloIdealMin")
                        .HasPrecision(6, 2)
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("LocalOrbitalId");

                    b.ToTable("EstufasConfig");
                });

            modelBuilder.Entity("GlobalSoluction.Models.LeituraSensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataLeitura")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("SensorId")
                        .HasColumnType("int");

                    b.Property<decimal>("Valor")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("SensorId");

                    b.ToTable("LeiturasSensor");
                });

            modelBuilder.Entity("GlobalSoluction.Models.LocalOrbital", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DataAnalise")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("IncidenciaSolar")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("NivelRiscoRadiacao")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Observacoes")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Planeta")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("PossuiGeloSubterraneo")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("ProtecaoNatural")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Regiao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("LocaisOrbitais");
                });

            modelBuilder.Entity("GlobalSoluction.Models.Sensor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("DataInstalacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EstufaConfigId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("TipoSensor")
                        .HasColumnType("int");

                    b.Property<string>("UnidadeMedida")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("EstufaConfigId");

                    b.ToTable("Sensores");
                });

            modelBuilder.Entity("GlobalSoluction.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("GlobalSoluction.Models.AlertaEstufa", b =>
                {
                    b.HasOne("GlobalSoluction.Models.EstufaConfig", "EstufaConfig")
                        .WithMany("Alertas")
                        .HasForeignKey("EstufaConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("GlobalSoluction.Models.Sensor", "Sensor")
                        .WithMany("Alertas")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("EstufaConfig");

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("GlobalSoluction.Models.EstufaConfig", b =>
                {
                    b.HasOne("GlobalSoluction.Models.LocalOrbital", "LocalOrbital")
                        .WithMany("Estufas")
                        .HasForeignKey("LocalOrbitalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("LocalOrbital");
                });

            modelBuilder.Entity("GlobalSoluction.Models.LeituraSensor", b =>
                {
                    b.HasOne("GlobalSoluction.Models.Sensor", "Sensor")
                        .WithMany("Leituras")
                        .HasForeignKey("SensorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sensor");
                });

            modelBuilder.Entity("GlobalSoluction.Models.Sensor", b =>
                {
                    b.HasOne("GlobalSoluction.Models.EstufaConfig", "EstufaConfig")
                        .WithMany("Sensores")
                        .HasForeignKey("EstufaConfigId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EstufaConfig");
                });

            modelBuilder.Entity("GlobalSoluction.Models.EstufaConfig", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Sensores");
                });

            modelBuilder.Entity("GlobalSoluction.Models.LocalOrbital", b =>
                {
                    b.Navigation("Estufas");
                });

            modelBuilder.Entity("GlobalSoluction.Models.Sensor", b =>
                {
                    b.Navigation("Alertas");

                    b.Navigation("Leituras");
                });
#pragma warning restore 612, 618
        }
    }
}
